### ISSUE TITLE
SBS locks out the editing box

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#140]
### Installed Version: 2.0.2 Dev G  Environment: Firefox/Greasemonkey 
This also occurred in some prior versions, I think in the prior generation.  

---
###  Expected Behavior
This not happening.

---
### Actual Behavior
When editing in SBS mode (today it was a new question; I don't recall the nature of prior posts when this happened), the edit box becomes inaccessible after clicking on another Firefox tab and returning.  Items outside the edit box remain operational.  The edit box, including the edit menu, are not selectable or responsive, like the entire edit box and menu is just a picture of it.  There is no editing cursor inside the box, just the normal screen cursor.

Refreshing the page opened a warning message about leaving the page, but the refresh restored the ability to edit (and the refresh deselected SBS).

This recurred several times.  Each time, I reselected SBS and was able to continue editing.  Then clicking on another FF tab and returning triggered the problem again.

Deselecting SBS then worked normally, with no further repetitions.

![su sbs](https://cloud.githubusercontent.com/assets/10065766/19990040/ee738b28-a200-11e6-8718-15cb7d84cd14.png)

After posting this, I went back to the same dummy question and found that the system was no longer displaying the duplicate question hints or tag suggestions.  Jumping to another tab did not trigger the locking.  I managed to trigger the question suggestions again.  Still, jumping to another tab didn't trigger the problem.  

That might suggest that the problem is triggered by the tag suggestions, or those in combination with the question suggestions.  However, I couldn't figure out how to re-trigger the tag suggestions to test this.

Update: It might actually be the tag suggestions (possibly in combination with the question suggestions).  After being unable to trigger the problem with the question suggestions displayed, I went back into the dummy question and started adding more keywords (the question suggestions continued to be displayed).  With a few more words, it popped up a list of suggested tags.  The edit box immediately locked when the suggested tags were displayed (without even jumping to another tab).

Update 2: I went back to the dummy question and the system was no longer displaying either duplicate question suggestions or tag suggestions.  I started adding keywords to the body, and the system popped up only the tag suggestions.  That immediately locked the edit box.  So it looks like it's just the tag suggestions.  

I'm not sure how jumping FF tabs is related.  That previously triggered this in the same way.  So either it's timing coincidence and it was just the tag suggestions, or either one can do it under certain conditions that still haven't been identified.

---
### SOX Errors logged to the browser console (if available)
I opened and cleared the console, then refreshed the Ask Question page and started experimenting.
```
The connection to ws://qa.sockets.stackexchange.com/ was interrupted while the page was loading. sox.features.js:1637:20
The connection to wss://qa.sockets.stackexchange.com/ was interrupted while the page was loading. full.en.js:1:6864
GET 
http://superuser.com/questions/ask [HTTP/1.1 200 OK 40ms]
GET 
http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js [HTTP/1.1 304 Not Modified 39ms]
GET 
http://cdn.sstatic.net/Js/stub.en.js [HTTP/1.1 304 Not Modified 27ms]
GET 
http://cdn.sstatic.net/Sites/superuser/all.css [HTTP/1.1 304 Not Modified 26ms]
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 304 Not Modified 21ms]
GET 
https://www.google-analytics.com/analytics.js [HTTP/2.0 304 Not Modified 13ms]
GET 
http://edge.quantserve.com/quant.js [HTTP/1.1 304 Not Modified 34ms]
GET 
http://b.scorecardresearch.com/beacon.js [HTTP/1.1 200 OK 12ms]
GET 
http://cdn.sstatic.net/img/share-sprite-new.svg [HTTP/1.1 304 Not Modified 12ms]
GET 
http://cdn.sstatic.net/Sites/superuser/img/sprites.svg [HTTP/1.1 304 Not Modified 12ms]
SOX:  undefined sox.common.js:8:13
SOX:  Object { init: StackExchange.init</<(o, s), debug: Object, initialized: Object, ready: StackExchange.ready(e), using: v(e, n, i, a), ifUsing: b(e, t, n), loadJsFile: StackExchange.loadJsFile(e, t), loadJqueryUi: StackExchange.loadJqueryUi(), helpers: Object, switchMobile: StackExchange.switchMobile(e), 5 more… } sox.common.js:8:13
GET 
http://b.scorecardresearch.com/b [HTTP/1.1 204 No Content 14ms]
GET 
http://cdn.sstatic.net/Js/full.en.js [HTTP/1.1 304 Not Modified 11ms]
GET 
http://cdn.sstatic.net/Js/tageditornew.en.js [HTTP/1.1 304 Not Modified 11ms]
GET 
http://cdn.sstatic.net/Js/tagsuggestions.en.js [HTTP/1.1 304 Not Modified 14ms]
GET 
http://cdn.sstatic.net/Js/wmd.en.js [HTTP/1.1 304 Not Modified 13ms]
XrayWrapper denied access to property "ready" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported. sox.common.js:51:0
GET 
https://www.google-analytics.com/collect [HTTP/2.0 200 OK 12ms]
GET 
https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css [HTTP/2.0 304 Not Modified 17ms]
SOX:  initializing SOX dialog sox.common.js:32:13
GET 
http://pixel.quantserve.com/pixel;r=1468243683;a=p-c1rF4kxgLUzNc;fpan=0;fpa=P0-2087723673-1465952398859;ns=0;ce=1;cm=;je=1;sr=2048x1152x24;enc=n;dst=1;et=1478215966754;tzo=240;ref=http%3A%2F%2Fsuperuser.com%2Freview;url=http%3A%2F%2Fsuperuser.com%2Fquestions%2Fask;ogl=type.website%2Cimage.http%3A%2F%2Fcdn%252Esstatic%252Enet%2FSites%2Fsuperuser%2Fimg%2Fapple-touch-icon%402%252Epng%3Fv%3De869e4459439%2Ctitle.Ask%20a%20Question%2Cdescription.Q%26A%20for%20computer%20enthusiasts%20and%20power%20users%2Curl.http%3A%2F%2Fsuperuser%252Ecom%2Fquestions%2Fask [HTTP/1.1 200 OK 29ms]
SOX:  injecting features into dialog sox.common.js:32:13
SOX:  observe: .inbox-dialog sox.common.js:8:13
SOX:  observe: .new_comment sox.common.js:8:13
SOX:  SOX Access Token: SET sox.common.js:8:13
SOX:  observe: .new_comment sox.common.js:8:13
SOX:  observe: li[id^="wmd-redo-button"] sox.common.js:8:13
SOX:  observe: li[id^="wmd-redo-button"], textarea[id^="wmd-input"] sox.common.js:8:13
SOX:  observe: [id^="wmd-redo-button"] sox.common.js:8:13
SOX:  observe: .image-upload form sox.common.js:8:13
SOX:  Object {  } sox.common.js:8:13
SOX:  Object {  } sox.common.js:8:13
SOX:  observe: .share-tip sox.common.js:8:13
GET 
http://cdn.sstatic.net/Js/post-validation.en.js [HTTP/1.1 304 Not Modified 13ms]
GET 
http://cdn.sstatic.net/Js/external-editor.en.js [HTTP/1.1 304 Not Modified 12ms]
POST 
http://superuser.com/gps/event [HTTP/1.1 204 No Content 25ms]
GET 
XHR 
https://api.stackexchange.com/2.2/users/ [HTTP/1.1 200 OK 70ms]
GET 
https://rawgit.com/shu8/SE-Answers_scripts/master/dupeClosedMigratedCSS.css [HTTP/2.0 304 Not Modified 40ms]
GET 
XHR 
https://api.stackexchange.com/users/ [HTTP/1.1 400 Bad Request 20ms]
GET 
XHR 
https://query.yahooapis.com/v1/public/yql [HTTP/2.0 200 OK 51ms]
GET 
XHR 
https://api.stackexchange.com/2.2/questions [HTTP/1.1 400 Bad Request 23ms]
GET 
https://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 87ms]
SOX:  fire: li[id^="wmd-redo-button"] sox.common.js:8:13
SOX:  fire: li[id^="wmd-redo-button"], textarea[id^="wmd-input"] sox.common.js:8:13
SOX:  fire: [id^="wmd-redo-button"] sox.common.js:8:13
GET 
http://cdn.sstatic.net/Sites/superuser/img/wmd-buttons.svg [HTTP/1.1 304 Not Modified 11ms]
GET 
XHR 
https://l.ghostery.com/api/page/ [HTTP/1.1 204 No Content 20ms]
GET 
http://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 63ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 19ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 22ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 23ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 26ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 26ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 29ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 37ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 42ms]
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:2:40351
POST 
http://superuser.com/gps/event [HTTP/1.1 204 No Content 29ms]
GET 
XHR 
http://superuser.com/questions/ticks [HTTP/1.1 200 OK 22ms]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
 full.en.js:6:9475
POST 
http://superuser.com/gps/event [HTTP/1.1 204 No Content 32ms]
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 42ms]
POST 
XHR 
http://superuser.com/posts/validate-body [HTTP/1.1 200 OK 29ms]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data sox.features.js:1643:29
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 31ms]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data sox.features.js:1643:29
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 31ms]
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 32ms]
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 30ms]
POST 
XHR 
http://superuser.com/posts/validate-body [HTTP/1.1 200 OK 24ms]
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 409 Conflict 24ms]
POST 
XHR 
http://superuser.com/posts/validate-body [HTTP/1.1 200 OK 30ms]
GET 
http://superuser.com/content/img/progress-dots.gif [HTTP/1.1 304 Not Modified 30ms]
GET 
XHR 
http://superuser.com/search/titles [HTTP/1.1 200 OK 39ms]
GET 
XHR 
http://superuser.com/search/titles [HTTP/1.1 200 OK 187ms]
POST 
http://superuser.com/gps/event [HTTP/1.1 204 No Content 26ms]
GET 
XHR 
http://superuser.com/search/titles [HTTP/1.1 200 OK 58ms]
POST 
http://superuser.com/gps/event [HTTP/1.1 204 No Content 25ms]
POST 
https://safebrowsing.google.com/safebrowsing/downloads [HTTP/2.0 200 OK 121ms]
GET 
https://safebrowsing-cache.google.com/safebrowsing/rd/ChVnb29nLWJhZGJpbnVybC1zaGF2YXI4AEACSgwIARDOkQcYz5EHIAFKDAgAEI7-BhiO_gYgAQ [HTTP/2.0 200 OK 194ms]
GET 
https://safebrowsing-cache.google.com/safebrowsing/rd/ChNnb29nLW1hbHdhcmUtc2hhdmFyOABAAkoMCAEQoIsPGKGLDyABSgwIABDurw8Y768PIAE [HTTP/2.0 200 OK 14ms]
GET 
https://safebrowsing-cache.google.com/safebrowsing/rd/ChFnb29nLXBoaXNoLXNoYXZhcjgAQAJKDAgBEJKCEhiTghIgAUoMCAAQmqccGJunHCAB [HTTP/2.0 200 OK 15ms]
GET 
https://safebrowsing-cache.google.com/safebrowsing/rd/ChRnb29nLXVud2FudGVkLXNoYXZhcjgAQAJKDAgBENzWBBjc1gQgAUoMCAAQkfQEGJL0BCAB [HTTP/2.0 200 OK 14ms]
GET 
XHR 
http://superuser.com/search/titles [HTTP/1.1 200 OK 49ms]
POST 
http://superuser.com/gps/event [HTTP/1.1 204 No Content 30ms]
POST 
http://superuser.com/gps/event [HTTP/1.1 204 No Content 24ms]
POST 
XHR 
http://superuser.com/posts/validate-title [HTTP/1.1 200 OK 26ms]
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 26ms]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data sox.features.js:1643:29
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 64ms]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data sox.features.js:1643:29
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 68ms]
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 70ms]
POST 
XHR 
http://superuser.com/posts/validate-body [HTTP/1.1 200 OK 24ms]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data sox.features.js:1643:29
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 66ms]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data sox.features.js:1643:29
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 122ms]
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 104ms]
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 196ms]
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 58ms]
POST 
XHR 
http://superuser.com/posts/validate-body [HTTP/1.1 200 OK 25ms]
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 503 backend read error 19ms]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data sox.features.js:1643:29
POST 
XHR 
http://superuser.com/posts/validate-body [HTTP/1.1 200 OK 42ms]
POST 
https://api.accounts.firefox.com/v1/certificate/sign [HTTP/1.1 200 OK 369ms]
GET 
https://token.services.mozilla.com/1.0/sync/1.5 [HTTP/1.1 200 OK 373ms]
GET 
https://sync-371-us-west-2.sync.services.mozilla.com/1.5/51738684/info/collections [HTTP/1.1 200 OK 321ms]
POST 
https://sync-371-us-west-2.sync.services.mozilla.com/1.5/51738684/storage/tabs [HTTP/1.1 200 OK 144ms]
GET 
https://github.com/soscripted/sox/issues/140 [HTTP/1.1 200 OK 358ms]
Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead. <unknown>
GET 
https://assets-cdn.github.com/assets/frameworks-119461b8a22c3dc631a815795aa9d7f436fe38386cd99a1ca106fd2798f159aa.css [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/assets/frameworks-35b9c541d341309b930b1c790fa1b27a30c7c44ce10c7f8242890e3d83c8adbd.js [HTTP/1.1 200 OK 0ms]
GET 
https://assets-cdn.github.com/assets/github-1a723b55b2ef1be875b55a21594ed7186180bb2530537ef3b195039fd4be0228.css [HTTP/1.1 200 OK 0ms]
GET 
https://avatars2.githubusercontent.com/u/10065766 [HTTP/1.1 304 Not Modified 17ms]
GET 
https://avatars0.githubusercontent.com/u/8850830 [HTTP/1.1 304 Not Modified 19ms]
GET 
https://avatars1.githubusercontent.com/u/10065766 [HTTP/1.1 304 Not Modified 22ms]
GET 
https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif [HTTP/1.1 200 OK 0ms]
GET 
https://avatars3.githubusercontent.com/u/8850830 [HTTP/1.1 304 Not Modified 24ms]
GET 
https://avatars2.githubusercontent.com/u/8850830 [HTTP/1.1 304 Not Modified 36ms]
GET 
https://assets-cdn.github.com/assets/github-069726d26b6defbe6af3336055d54c25b1f41ab0a5e0d43d2cc7eff1c22a26f7.js [HTTP/1.1 200 OK 0ms]
GET 
https://avatars3.githubusercontent.com/u/10065766 [HTTP/1.1 304 Not Modified 13ms]
Content Security Policy: The page's settings blocked the loading of a resource at about:blank ("base-uri https://github.com"). <unknown>
call to eval() blocked by CSP <unknown>
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create frameworks-35b9c541d341309b930b1c790fa1b27a30c7c44ce10c7f8242890e3d83c8adbd.js:1:19194
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://assets-cdn.github.com"). sox.common.js:37:0
GET 
XHR 
https://github.com/soscripted/sox/issues/140/show_partial [HTTP/1.1 200 OK 56ms]
Empty string passed to getElementById(). github-069726d26b6defbe6af3336055d54c25b1f41ab0a5e0d43d2cc7eff1c22a26f7.js:4:21671
Empty string passed to getElementById(). github-069726d26b6defbe6af3336055d54c25b1f41ab0a5e0d43d2cc7eff1c22a26f7.js:8:28554
GET 
https://collector.githubapp.com/github/page_view [HTTP/1.1 200 OK 90ms]
Empty string passed to getElementById(). frameworks-35b9c541d341309b930b1c790fa1b27a30c7c44ce10c7f8242890e3d83c8adbd.js:6:3986
POST 
XHR 
https://www.google-analytics.com/r/collect [HTTP/2.0 200 OK 109ms]
GET 
https://assets-cdn.github.com/images/icons/emoji/unicode/1f61e.png [HTTP/1.1 200 OK 0ms]
GET 
https://live.github.com/_sockets/MTAwNjU3NjY6YjIxZjQ1NWE5NjVkNjU2YzJjNWUyNmVhZjVhYTVmMDQ6NmI0NTg5MTg4NzljMmI0ODllOWZlNDBiZjIwODkwZTY5NTQ5MTYzMGQ3YmEyM2Y2ZjNmZTEyOGMwOThkZjlkNQ==--c001f1e0c9dcea54cef16a60e5b5f58ef545960e [HTTP/1.1 101 Switching Protocols 81ms]
GET 
XHR 
https://l.ghostery.com/api/page/ [HTTP/1.1 204 No Content 116ms]
POST 
XHR 
https://api.github.com/_private/browser/stats [HTTP/1.1 200 OK 169ms]
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 32ms]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data sox.features.js:1643:29
POST 
https://shavar.services.mozilla.com/downloads [HTTP/1.1 200 OK 346ms]
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 4909ms]
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data sox.features.js:1643:29
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 30ms]
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
GET 
XHR 
http://superuser.com/tags/microsoft-word/subscriber-info [HTTP/1.1 200 OK 31ms]
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 34ms]
The connection to wss://qa.sockets.stackexchange.com/ was interrupted while the page was loading. full.en.js:1:6864
The connection to ws://qa.sockets.stackexchange.com/ was interrupted while the page was loading. sox.features.js:1637:20
GET 
http://superuser.com/questions/ask [HTTP/1.1 200 OK 50ms]
GET 
http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js [HTTP/1.1 304 Not Modified 38ms]
GET 
http://cdn.sstatic.net/Js/stub.en.js [HTTP/1.1 304 Not Modified 21ms]
GET 
http://cdn.sstatic.net/Sites/superuser/all.css [HTTP/1.1 304 Not Modified 24ms]
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 304 Not Modified 51ms]
GET 
https://www.google-analytics.com/analytics.js [HTTP/2.0 304 Not Modified 15ms]
GET 
http://edge.quantserve.com/quant.js [HTTP/1.1 304 Not Modified 33ms]
GET 
http://b.scorecardresearch.com/beacon.js [HTTP/1.1 200 OK 30ms]
GET 
http://cdn.sstatic.net/img/share-sprite-new.svg [HTTP/1.1 304 Not Modified 21ms]
GET 
http://cdn.sstatic.net/Sites/superuser/img/sprites.svg [HTTP/1.1 304 Not Modified 18ms]
SOX:  undefined sox.common.js:8:13
SOX:  Object { init: StackExchange.init</<(o, s), debug: Object, initialized: Object, ready: StackExchange.ready(e), using: v(e, n, i, a), ifUsing: b(e, t, n), loadJsFile: StackExchange.loadJsFile(e, t), loadJqueryUi: StackExchange.loadJqueryUi(), helpers: Object, switchMobile: StackExchange.switchMobile(e), 5 more… } sox.common.js:8:13
GET 
http://b.scorecardresearch.com/b [HTTP/1.1 204 No Content 14ms]
GET 
http://cdn.sstatic.net/Js/full.en.js [HTTP/1.1 304 Not Modified 13ms]
GET 
http://cdn.sstatic.net/Js/tageditornew.en.js [HTTP/1.1 304 Not Modified 11ms]
GET 
http://cdn.sstatic.net/Js/tagsuggestions.en.js [HTTP/1.1 304 Not Modified 13ms]
GET 
http://cdn.sstatic.net/Js/wmd.en.js [HTTP/1.1 304 Not Modified 10ms]
XrayWrapper denied access to property "ready" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported. sox.common.js:51:0
GET 
https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css [HTTP/2.0 304 Not Modified 120ms]
SOX:  initializing SOX dialog sox.common.js:32:13
GET 
https://www.google-analytics.com/r/collect [HTTP/2.0 200 OK 25ms]
GET 
http://pixel.quantserve.com/pixel;r=1928256648;a=p-c1rF4kxgLUzNc;fpan=0;fpa=P0-2087723673-1465952398859;ns=0;ce=1;cm=;je=1;sr=2048x1152x24;enc=n;dst=1;et=1478216730855;tzo=240;ref=http%3A%2F%2Fsuperuser.com%2Freview;url=http%3A%2F%2Fsuperuser.com%2Fquestions%2Fask;ogl=type.website%2Cimage.http%3A%2F%2Fcdn%252Esstatic%252Enet%2FSites%2Fsuperuser%2Fimg%2Fapple-touch-icon%402%252Epng%3Fv%3De869e4459439%2Ctitle.Ask%20a%20Question%2Cdescription.Q%26A%20for%20computer%20enthusiasts%20and%20power%20users%2Curl.http%3A%2F%2Fsuperuser%252Ecom%2Fquestions%2Fask [HTTP/1.1 200 OK 36ms]
SOX:  injecting features into dialog sox.common.js:32:13
SOX:  observe: .inbox-dialog sox.common.js:8:13
SOX:  observe: .new_comment sox.common.js:8:13
SOX:  SOX Access Token: SET sox.common.js:8:13
SOX:  observe: .new_comment sox.common.js:8:13
SOX:  observe: li[id^="wmd-redo-button"] sox.common.js:8:13
SOX:  observe: li[id^="wmd-redo-button"], textarea[id^="wmd-input"] sox.common.js:8:13
SOX:  observe: [id^="wmd-redo-button"] sox.common.js:8:13
SOX:  observe: .image-upload form sox.common.js:8:13
SOX:  Object {  } sox.common.js:8:13
SOX:  Object {  } sox.common.js:8:13
SOX:  observe: .share-tip sox.common.js:8:13
GET 
http://cdn.sstatic.net/Js/post-validation.en.js [HTTP/1.1 304 Not Modified 12ms]
GET 
http://cdn.sstatic.net/Js/external-editor.en.js [HTTP/1.1 304 Not Modified 14ms]
POST 
http://superuser.com/gps/event [HTTP/1.1 204 No Content 25ms]
GET 
XHR 
https://query.yahooapis.com/v1/public/yql [HTTP/2.0 200 OK 220ms]
GET 
XHR 
https://api.stackexchange.com/2.2/questions [HTTP/1.1 400 Bad Request 114ms]
GET 
https://rawgit.com/shu8/SE-Answers_scripts/master/dupeClosedMigratedCSS.css [HTTP/2.0 304 Not Modified 464ms]
GET 
XHR 
https://api.stackexchange.com/users/ [HTTP/1.1 400 Bad Request 23ms]
GET 
XHR 
https://api.stackexchange.com/2.2/users/ [HTTP/1.1 200 OK 122ms]
SOX:  fire: li[id^="wmd-redo-button"] sox.common.js:8:13
SOX:  fire: li[id^="wmd-redo-button"], textarea[id^="wmd-input"] sox.common.js:8:13
SOX:  fire: [id^="wmd-redo-button"] sox.common.js:8:13
GET 
https://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 105ms]
GET 
http://cdn.sstatic.net/Sites/superuser/img/wmd-buttons.svg [HTTP/1.1 304 Not Modified 15ms]
GET 
http://qa.sockets.stackexchange.com/ [HTTP/1.1 101 Switching Protocols 67ms]
GET 
XHR 
https://l.ghostery.com/api/page/ [HTTP/1.1 204 No Content 237ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 174ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 155ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 165ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 156ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 160ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 170ms]
GET 
XHR 
https://l.ghostery.com/api/census [HTTP/1.1 204 No Content 176ms]
POST 
http://superuser.com/gps/event [HTTP/1.1 204 No Content 30ms]
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:2:40351
POST 
http://superuser.com/gps/event [HTTP/1.1 204 No Content 25ms]
POST 
XHR 
http://superuser.com/posts/validate-body [HTTP/1.1 200 OK 30ms]
POST 
XHR 
http://superuser.com/posts/validate-body [HTTP/1.1 200 OK 32ms]
GET 
XHR 
http://superuser.com/questions/ticks [HTTP/1.1 200 OK 27ms]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
 full.en.js:6:9475
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 60ms]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data sox.features.js:1643:29
POST 
XHR 
http://superuser.com/posts/0/editor-heartbeat/ask [HTTP/1.1 200 OK 64ms]
POST 
XHR 
http://superuser.com/posts/validate-body [HTTP/1.1 200 OK 33ms]
POST 
XHR 
http://superuser.com/posts/validate-body [HTTP/1.1 200 OK 32ms]
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create panel.js:5816:3
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ panel.js:3525:3
not well-formed messages.json:1:1
```

---
### Steps to reproduce
Open the Ask Question page, turn on SBS, and start entering a question.  Click on another FF tab, then return to the Ask Question tab.  The edit box will be locked.

At the point I discovered that, I had already entered enough key words to trigger the suggestions of similar questions and tag suggestions, which are both unique to this page.  They were present when the problem occurred.  I haven't tested jumping to another tab before that point.

**Comment by shu8** [comment]
@fixer1234 thanks for the report; I'll keep my eye out for it :) If you notice it again, please could you take a screenshot and the console (although I have a feeling it won't be that helpful... 😞)?

**Comment by fixer1234** [comment]
@shu8 Discovered the trigger and updated the issue.

**Comment by shu8** [comment]
@fixer1234 I can't seem to reproduce this on FF or Chrome. 

Can you repeatedly repro it by starting a question, going to a different tab, and coming back? Or does it only happen sometimes?

**Comment by fixer1234** [comment]
@shu8 As mentioned in the updated issue post, the tabbing may have been coincidental.  A lot of issues seem to be changing behavior.  But when the tag suggestions are not displayed, the tabbing no longer seems to trigger it.  As far as I can determine, it is the system's display of tag suggestions that triggers the locking.

**Comment by fixer1234** [comment]
@shu8 I just loaded Dev P and figured I'd verify this.  The tag suggestions are definitely what triggers it.  In addition to testing just the tag suggestions, I experimented with the tabbing.  I added a keyword and the editor did not immediately add the tag suggestions.  However, when I tabbed away and then clicked back, the tag suggestions were generated, which locked the edit box.  So that could have been the tabbing connection previously.

**Comment by shu8** [comment]
@fixer1234 How do you get the tag suggestions to come up? I've tried entering various words such as `windows` and `monitor`, etc... with no luck :(

**Comment by shu8** [comment]
@fixer1234 actually not too hard a fix! :D 

fixed in [dev r](https://github.com/soscripted/sox/raw/dev/sox.user.js)

**Comment by fixer1234** [comment]
@shu8 It was a pain in the butt trying to trick the UI into displaying tag suggestions (apparently, it's smarter than just looking for key words).  But I finally got it to display and it looks like you fixed it.  Confirming another one.
